### ISSUE TITLE
Proxy a proxy class

### ISSUE THREAD

**Issue by jhrldev** [JonathanxD/CodeProxy#4]
Support proxy a KoresProxy proxy class.

Currently KoresProxy generated proxy class fails to be _proxied_ because of proxy generated parameters not being provided to proxy super class through constructs. Instead it enforces that you provide both `InvocationHandler` and `ProxyData` manually, which is designed to be automatically provided through proxing logic.

## Motivation

This would allow generate delegation to dummy proxies.

**Comment by JonathanxD** [comment]
Fixed in [2.5.8](https://github.com/koresframework/KoresProxy/releases/tag/2.5.8) by 3fe11e4af7b026e2661fe69fa139e56fdda78497
